swagger: '2.0'
info:
  title: User Management API
  version: 1.0.0
  description: API for managing user interactions such as sending and accepting friend requests, following users, etc.
paths:
  /api/users/acceptRequest/{id}:
    put:
      summary: Accept a friend request
      description: Allows the authenticated user to accept a friend request from another user.
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user who sent the friend request.
          type: string
          example: 60d0fe4f5311236168a109d8
      responses:
        200:
          description: Successfully accepted the friend request.
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              code:
                type: string
                example: FRIEND_REQUEST_ACCEPTED
              message:
                type: string
                example: Friend request successfully accepted.
        400:
          description: Invalid action, friend request not found, or trying to accept a request from yourself.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: INVALID_ACTION
              message:
                type: string
                example: You can't accept a request from yourself.
        404:
          description: User not found or friend request not found.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: USER_NOT_FOUND
              message:
                type: string
                example: User not found.
        500:
          description: Internal server error.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: SERVER_ERROR
              message:
                type: string
                example: An unexpected error occurred. Please try again later.
