swagger: '2.0'
info:
  title: User Search History API
  version: 1.0.0
  description: API documentation for adding a user to the search history.
paths:
  /api/users/addToSearchHistory:
    put:
      summary: Add a user to the search history
      description: Endpoint to add a user to the authenticated user's search history.
      tags:
        - Users
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              searchUser:
                type: string
                description: The ObjectId of the user to add to the search history.
                example: 60b8d095d4e7c4f94588f7d1
            required:
              - searchUser
      responses:
        '200':
          description: Search history updated successfully.
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              code:
                type: string
                example: SEARCH_HISTORY_UPDATED
              message:
                type: string
                example: Search history updated successfully.
              data:
                type: object
                properties:
                  search:
                    type: array
                    items:
                      type: object
                      properties:
                        first_name:
                          type: string
                          example: John
                        last_name:
                          type: string
                          example: Doe
                        username:
                          type: string
                          example: johndoe123
                        picture:
                          type: string
                          example: /path/to/profile/picture
        '400':
          description: Missing search user or invalid search user ID.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: SEARCH_USER_REQUIRED
              message:
                type: string
                example: Search user is required.
        '401':
          description: Unauthorized access.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: UNAUTHORIZED
              message:
                type: string
                example: You are not authorized to perform this action.
        '500':
          description: Internal server error.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: SERVER_ERROR
              message:
                type: string
                example: An unexpected error occurred. Please try again later.
