swagger: '2.0'
info:
  title: User Management API
  version: 1.0.0
  description: API for managing user interactions such as sending and canceling friend requests, following users, etc.
paths:
  /api/users/cancelRequest/{id}:
    put:
      summary: Cancel a sent friend request
      description: Allows the authenticated user to cancel a friend request they previously sent to another user.
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user to cancel the friend request for.
          type: string
          example: 60d0fe4f5311236168a109d8
      responses:
        200:
          description: Friend request canceled successfully.
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              code:
                type: string
                example: FRIEND_REQUEST_CANCELED
              message:
                type: string
                example: Friend request canceled successfully.
        400:
          description: Invalid action, friend request not found, or already friends.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: INVALID_ACTION
              message:
                type: string
                example: You can't send a friend request to yourself.
        404:
          description: User not found.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: USER_NOT_FOUND
              message:
                type: string
                example: User not found.
        500:
          description: Internal server error.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: SERVER_ERROR
              message:
                type: string
                example: An unexpected error occurred. Please try again later.
