swagger: '2.0'
info:
  title: User Management API
  version: 1.0.0
  description: API for managing user interactions such as following users and sending friend requests.
paths:
  /api/users/follow/{id}:
    put:
      summary: Follow a user
      description: Allows the authenticated user to follow another user.
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user to follow.
          type: string
          example: 60d0fe4f5311236168a109d8
      responses:
        200:
          description: Successfully followed the user.
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              code:
                type: string
                example: FOLLOW_SUCCESS
              message:
                type: string
                example: You successfully followed the user.
        400:
          description: Invalid action, already following, or trying to follow yourself.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: INVALID_ACTION
              message:
                type: string
                example: You can't follow yourself.
        404:
          description: User not found.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: USER_NOT_FOUND
              message:
                type: string
                example: User not found.
        500:
          description: Internal server error.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: SERVER_ERROR
              message:
                type: string
                example: An unexpected error occurred. Please try again later.
