swagger: '2.0'
info:
  title: "Get Friends Page Infos Route"
  version: 1.0.0
  description: "API endpoint for retrieving friends page information."
paths:
  /api/users/getFriendsPageInfos:
    get:
      summary: Get friends page information
      description: Retrieves the list of friends, friend requests, and sent friend requests for the authenticated user.
      tags:
        - Users
      responses:
        200:
          description: Successfully retrieved the friends page information.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  code:
                    type: string
                    example: FRIENDS_PAGE_INFO
                  message:
                    type: string
                    example: Friends page information retrieved successfully.
                  data:
                    type: object
                    properties:
                      friends:
                        type: array
                        items:
                          type: object
                          properties:
                            first_name:
                              type: string
                              example: John
                            last_name:
                              type: string
                              example: Doe
                            picture:
                              type: string
                              example: "http://example.com/pic.jpg"
                            username:
                              type: string
                              example: john_doe
                      requests:
                        type: array
                        items:
                          type: object
                          properties:
                            first_name:
                              type: string
                              example: Jane
                            last_name:
                              type: string
                              example: Smith
                            picture:
                              type: string
                              example: "http://example.com/pic.jpg"
                            username:
                              type: string
                              example: jane_smith
                      sentRequests:
                        type: array
                        items:
                          type: object
                          properties:
                            first_name:
                              type: string
                              example: Alice
                            last_name:
                              type: string
                              example: Brown
                            picture:
                              type: string
                              example: "http://example.com/pic.jpg"
                            username:
                              type: string
                              example: alice_brown
        400:
          description: User not found (either the user is not authenticated or does not exist).
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: USER_NOT_FOUND
                  message:
                    type: string
                    example: User not found.
        404:
          description: User not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: USER_NOT_FOUND
                  message:
                    type: string
                   
