swagger: '2.0'
info:
  title: User Search History API
  version: 1.0.0
  description: API documentation for user profile management.
paths:
  /api/users/getProfile/{username}:
    get:
      summary: Get a user profile by username
      description: Retrieve a user's profile, including their posts and friendship status with the authenticated user.
      tags:
        - Users
      parameters:
        - in: path
          name: username
          required: true
          description: The username of the user whose profile is to be retrieved.
          type: string
          example: johndoe123
      responses:
        '200':
          description: User profile retrieved successfully.
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              code:
                type: string
                example: PROFILE_RETRIEVED
              message:
                type: string
                example: Profile retrieved successfully.
              data:
                type: object
                properties:
                  _id:
                    type: string
                    example: 605c72ef7c8e4f0f0f2a5b77
                  first_name:
                    type: string
                    example: John
                  last_name:
                    type: string
                    example: Doe
                  username:
                    type: string
                    example: johndoe123
                  picture:
                    type: string
                    example: /path/to/profile/picture
                  posts:
                    type: array
                    items:
                      type: object
                      properties:
                        content:
                          type: string
                          example: This is a post.
                        createdAt:
                          type: string
                          format: date-time
                          example: 2024-12-07T12:34:56Z
                        comments:
                          type: array
                          items:
                            type: object
                            properties:
                              comment:
                                type: string
                                example: Nice post!
                              commentBy:
                                type: object
                                properties:
                                  first_name:
                                    type: string
                                    example: Jane
                                  last_name:
                                    type: string
                                    example: Smith
                                  picture:
                                    type: string
                                    example: /path/to/commenter/picture
                                  username:
                                    type: string
                                    example: janesmith
                              commentAt:
                                type: string
                                format: date-time
                                example: 2024-12-07T12:35:30Z
                  friendship:
                    type: object
                    properties:
                      friends:
                        type: boolean
                        example: true
                      following:
                        type: boolean
                        example: false
                      requestSent:
                        type: boolean
                        example: true
                      requestReceived:
                        type: boolean
                        example: false
        '404':
          description: Profile not found or user not authenticated.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: PROFILE_NOT_FOUND
              message:
                type: string
                example: Profile not found.
        '500':
          description: Internal server error.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: SERVER_ERROR
              message:
                type: string
                example: An unexpected error occurred. Please try again later.
