swagger: '2.0'
info:
  title: User Search History API
  version: 1.0.0
  description: API documentation for retrieving the search history of the authenticated user.
paths:
  /api/users/getSearchHistory:
    get:
      summary: Retrieve the search history of the authenticated user
      description: Endpoint to retrieve the search history of the authenticated user.
      tags:
        - Users
      responses:
        '200':
          description: Search history retrieved successfully.
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              code:
                type: string
                example: SEARCH_HISTORY_RETRIEVED
              message:
                type: string
                example: Search history retrieved successfully.
              data:
                type: object
                properties:
                  search:
                    type: array
                    items:
                      type: object
                      properties:
                        first_name:
                          type: string
                          example: John
                        last_name:
                          type: string
                          example: Doe
                        username:
                          type: string
                          example: johndoe123
                        picture:
                          type: string
                          example: /path/to/profile/picture
        '401':
          description: Unauthorized access.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: UNAUTHORIZED
              message:
                type: string
                example: You are not authorized to perform this action.
        '500':
          description: Internal server error.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: SERVER_ERROR
              message:
                type: string
                example: An unexpected error occurred. Please try again later.
