swagger: '2.0'
info:
  title: User Search History API
  version: 1.0.0
  description: API documentation for removing a user from the search history.
paths:
  /api/users/removeFromSearchHistory:
    put:
      summary: Remove a user from the search history of the authenticated user
      description: Endpoint to remove a specific user from the authenticated user's search history.
      tags:
      - Users
      parameters:
      - in: body
        name: body
        required: true
        schema:
          type: object
          properties:
            searchUserId:
              type: string
              description: The ID of the user to be removed from the search history.
              example: 605c72ef7c8e4f0f0f2a5b77
          required:
          - searchUserId
      responses:
        '200':
          description: User successfully removed from search history.
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              code:
                type: string
                example: SEARCH_USER_REMOVED
              message:
                type: string
                example: User successfully removed from search history.
              data:
                type: object
                properties:
                  search:
                    type: array
                    items:
                      type: object
                      properties:
                        first_name:
                          type: string
                          example: John
                        last_name:
                          type: string
                          example: Doe
                        username:
                          type: string
                          example: johndoe123
                        picture:
                          type: string
                          example: /path/to/profile/picture
        '400':
          description: Missing searchUserId in the request body.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: SEARCH_USER_ID_REQUIRED
              message:
                type: string
                example: Search user ID is required.
        '401':
          description: Unauthorized access.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: UNAUTHORIZED
              message:
                type: string
                example: You are not authorized to perform this action.
        '500':
          description: Internal server error.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: SERVER_ERROR
              message:
                type: string
                example: An unexpected error occurred. Please try again later.
