swagger: '2.0'
info:
  title: User Search API
  version: 1.0.0
  description: API documentation for searching users by their email.
paths:
  /api/users/search-user:
    post:
      summary: Search user by email
      description: Endpoint to search for a user by their email address. Returns the user's basic details if found.
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: johndoe@example.com
                  description: The email address of the user to search for.
              required:
                - email
      responses:
        '200':
          description: User found successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  code:
                    type: string
                    example: USER_FOUND
                  message:
                    type: string
                    example: User found successfully.
                  data:
                    type: object
                    properties:
                      picture:
                        type: string
                        example: /profile/picture/url
                      first_name:
                        type: string
                        example: John
        '404':
          description: User not found with the given email address.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: USER_NOT_FOUND
                  message:
                    type: string
                    example: User not found with this email address.
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: SERVER_ERROR
                  message:
                    type: string
                    example: An unexpected error occurred. Please try again later.
