swagger: '2.0'
info:
  title: User Authentication API
  version: 1.0.0
  description: API documentation for handling user authentication tasks such as changing passwords.
paths:
  /api/auth/change-password:
    post:
      summary: Change user password
      description: Endpoint to allow users to change their current password to a new one.
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                currentPassword:
                  type: string
                  example: oldpassword123
                  description: The current password of the user.
                newPassword:
                  type: string
                  example: newpassword456
                  description: The new password the user wants to set.
              required:
                - currentPassword
                - newPassword
      responses:
        '200':
          description: Password changed successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  code:
                    type: string
                    example: PASSWORD_CHANGED
                  message:
                    type: string
                    example: Password changed successfully.
        '400':
          description: Bad request, likely due to invalid input or missing required fields.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: BAD_REQUEST
                  message:
                    type: string
                    example: Invalid input. Please check your request.
        '401':
          description: Unauthorized, current password is incorrect or user is not authenticated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: UNAUTHORIZED
                  message:
                    type: string
                    example: Current password is incorrect or you are not authorized to perform this action.
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: SERVER_ERROR
                  message:
                    type: string
                    example: An unexpected error occurred. Please try again later.
