swagger: '2.0'
info:
  title: "Unfriend Route"
  version: 1.0.0
  description: "API endpoint for unfriending a user."
paths:
  /api/users/unfriend/{id}:
    put:
      summary: Unfriend a user
      description: Allows the authenticated user to unfriend another user.
      tags:
        - Users
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user to unfriend.
          schema:
            type: string
            example: 60d0fe4f5311236168a109d8
      responses:
        200:
          description: Successfully unfriended the user.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  code:
                    type: string
                    example: FRIEND_UNFRIEND
                  message:
                    type: string
                    example: Friendship successfully unfriended.
        400:
          description: Invalid action, not friends, or trying to unfriend yourself.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: INVALID_ACTION
                  message:
                    type: string
                    example: You can't unfriend yourself.
        404:
          description: User not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: USER_NOT_FOUND
                  message:
                    type: string
                    example: User not found.
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: SERVER_ERROR
                  message:
                    type: string
                    example: An unexpected error occurred. Please try again later.
