swagger: '2.0'
info:
  title: User Management API
  version: 1.0.0
  description: API documentation for updating user details.
paths:
  /api/users/updateDetails:
    put:
      summary: Update user details
      description: Update the details of the authenticated user (e.g., biography, job, etc.).
      tags:
        - Users
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              infos:
                type: object
                description: New details to update (e.g., biography, job, etc.).
                example:
                  biography: "Software developer with a passion for coding."
                  job: "Senior Developer"
                  workPlace: "TechCorp"
                  highSchool: "Springfield High"
                  college: "Tech University"
                  currentCity: "New York"
                  homeTown: "Los Angeles"
      responses:
        '200':
          description: User details updated successfully.
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              code:
                type: string
                example: DETAILS_UPDATE
              message:
                type: string
                example: Details updated successfully.
              data:
                type: object
                properties:
                  details:
                    type: object
                    description: Updated user details.
                    example:
                      biography: "Software developer with a passion for coding."
                      job: "Senior Developer"
                      workPlace: "TechCorp"
                      highSchool: "Springfield High"
                      college: "Tech University"
                      currentCity: "New York"
                      homeTown: "Los Angeles"
        '404':
          description: User not found.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: USER_NOT_FOUND
              message:
                type: string
                example: User not found.
        '500':
          description: Internal server error.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: SERVER_ERROR
              message:
                type: string
                example: An unexpected error occurred. Please try again later.
