swagger: '2.0'
info:
  title: User Management API
  version: 1.0.0
  description: API documentation for updating user profile information.
paths:
  /api/users/updateProfilePicture:
    put:
      summary: Update profile picture
      description: Update the authenticated user's profile picture.
      tags:
        - Users
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              url:
                type: string
                description: URL of the new profile picture.
                example: /path/to/new/profile/picture.jpg
      responses:
        '200':
          description: Profile picture updated successfully.
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              code:
                type: string
                example: PROFILE_PICTURE_UPDATE
              message:
                type: string
                example: Profile picture updated successfully.
              data:
                type: object
                properties:
                  picture:
                    type: string
                    example: /path/to/new/profile/picture.jpg
        '404':
          description: User not found.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: USER_NOT_FOUND
              message:
                type: string
                example: User not found.
        '500':
          description: Internal server error.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: SERVER_ERROR
              message:
                type: string
                example: An unexpected error occurred. Please try again later.
