swagger: '2.0'
info:
  title: User Management API
  version: 1.0.0
  description: API documentation for updating user cover image.
paths:
  /api/users/updateCover:
    put:
      summary: Update cover image
      description: Update the authenticated user's cover image.
      tags:
        - Users
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              url:
                type: string
                description: URL of the new cover image.
                example: /path/to/new/cover/image.jpg
      responses:
        '200':
          description: Cover image updated successfully.
          schema:
            type: object
            properties:
              status:
                type: string
                example: success
              code:
                type: string
                example: COVER_UPDATE
              message:
                type: string
                example: Cover updated successfully.
              data:
                type: object
                properties:
                  cover:
                    type: string
                    example: /path/to/new/cover/image.jpg
        '404':
          description: User not found.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: USER_NOT_FOUND
              message:
                type: string
                example: User not found.
        '500':
          description: Internal server error.
          schema:
            type: object
            properties:
              status:
                type: string
                example: error
              code:
                type: string
                example: SERVER_ERROR
              message:
                type: string
                example: An unexpected error occurred. Please try again later.
