swagger: '2.0'
info:
  title: "Create Post API"
  version: 1.0.0
  description: "API for creating a new post for an authenticated user."

paths:
  /api/posts/createPost:
    post:
      summary: Create a new post
      description: Creates a new post for the authenticated user with the specified content.
      tags:
        - Posts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  example: "This is a new post."
                user:
                  type: string
                  example: "60d3b41abd4c3b4e8c1e10b3"  # User ID of the post creator
      responses:
        200:
          description: Post created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  code:
                    type: string
                    example: POST_CREATED
                  message:
                    type: string
                    example: "Post created successfully."
                  data:
                    type: object
                    properties:
                      post:
                        type: object
                        properties:
                          content:
                            type: string
                            example: "This is a new post."
                          user:
                            type: string
                            example: "60d3b41abd4c3b4e8c1e10b3"
                          createdAt:
                            type: string
                            example: "2024-12-07T15:00:00.000Z"
        400:
          description: Missing required fields in the request.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: MISSING_REQUIRED_FIELDS
                  message:
                    type: string
                    example: "Content or user is missing."
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: SERVER_ERROR
                  message:
                    type: string
                    example: "An unexpected error occurred. Please try again later."
