swagger: '2.0'
info:
  title: "Get All Posts API"
  version: 1.0.0
  description: "API for fetching all posts from users that the authenticated user is following."

paths:
  /api/posts/getAllPosts:
    get:
      summary: Get all posts from followed users
      description: Retrieves posts from users the authenticated user is following, including the user's own posts.
      tags:
        - Posts
      responses:
        200:
          description: Successfully fetched all posts.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  code:
                    type: string
                    example: POSTS_FETCHED
                  message:
                    type: string
                    example: "Posts fetched successfully."
                  data:
                    type: object
                    properties:
                      posts:
                        type: array
                        items:
                          type: object
                          properties:
                            content:
                              type: string
                              example: "This is a new post."
                            user:
                              type: string
                              example: "60d3b41abd4c3b4e8c1e10b3"
                            createdAt:
                              type: string
                              example: "2024-12-07T15:00:00.000Z"
        400:
          description: User ID is missing.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: USER_ID_MISSING
                  message:
                    type: string
                    example: "User ID is missing in the request."
        404:
          description: User not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: USER_NOT_FOUND
                  message:
                    type: string
                    example: "User not found."
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: SERVER_ERROR
                  message:
                    type: string
                    example: "An unexpected error occurred. Please try again later."
