swagger: '2.0'
info:
  title: "Save or Remove Post API"
  version: 1.0.0
  description: "API for saving or removing a post from the user's saved posts."

paths:
  /api/posts/savePost/{id}:
    put:
      summary: Save or remove a post from saved posts
      description: Allows the user to save a post or remove it from their saved posts list.
      tags:
        - Posts
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            example: "60d3b41abd4c3b4e8c1e10b5"
      responses:
        200:
          description: Post saved or removed from saved list.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  code:
                    type: string
                    example: POST_SAVED
                  message:
                    type: string
                    example: "Post saved successfully."
        404:
          description: User not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: USER_NOT_FOUND
                  message:
                    type: string
                    example: "User not found."
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: SERVER_ERROR
                  message:
                    type: string
                    example: "An unexpected error occurred. Please try again later."
