swagger: '2.0'
info:
  title: "File Upload API"
  version: 1.0.0
  description: "API documentation for uploading multiple files to the cloud."

paths:
  /api/uploads/uploadFilesToCloud:
    post:
      summary: Upload multiple files to the cloud
      description: Upload multiple files to a specified cloud folder.
      tags:
        - Uploads
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                folder:
                  type: string
                  example: "user-images"
                images:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        200:
          description: Files successfully uploaded to the cloud.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  code:
                    type: string
                    example: FILE_UPLOADED_TO_CLOUD
                  message:
                    type: string
                    example: "File uploaded to cloud successfully."
                  data:
                    type: object
                    properties:
                      files:
                        type: array
                        items:
                          type: object
                          properties:
                            fileUrl:
                              type: string
                              example: "https://cloud-storage.com/file1.jpg"
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: SERVER_ERROR
                  message:
                    type: string
                    example: "An unexpected error occurred. Please try again later."
