swagger: '2.0'
info:
  title: "File Upload API"
  version: 1.0.0
  description: "API documentation for uploading a single file."

paths:
  /api/uploads/uploadFile:
    post:
      summary: Upload a file to the server
      description: Upload a single file to the server and save it in a specified directory.
      tags:
        - Uploads
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        200:
          description: File successfully uploaded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  code:
                    type: string
                    example: FILE_UPLOADED
                  message:
                    type: string
                    example: "File uploaded successfully."
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: SERVER_ERROR
                  message:
                    type: string
                    example: "An unexpected error occurred. Please try again later."
