swagger: '2.0'
info:
  title: User Authentication API
  version: 1.0.0
  description: API for user authentication, including change password
  paths:
  /api/auth/changePassword:
    post:
      summary: Change a user's password
      description: Change a user's password.
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: The email address of the user whose password needs to be changed.
                  example: user@example.com
                password:
                  type: string
                  format: password
                  description: The new password for the user.
                  example: "newSecurePassword123"
      responses:
        '200':
          description: Password changed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  code:
                    type: string
                    example: PASSWORD_CHANGED
                  message:
                    type: string
                    example: Password changed successfully.
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: USER_NOT_FOUND
                  message:
                    type: string
                    example: User not found with this email address.
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: SERVER_ERROR
                  message:
                    type: string
                    example: An unexpected error occurred. Please try again later.
