swagger: '2.0'
info:
  title: User Authentication API
  version: 1.0.0
  description: API for user authentication, including registration functionality.
paths:
  /api/auth/register:
    post:
      summary: User registration
      description: Registers a new user and sends a verification email.
      tags:
      - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Registration successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          description: Missing or invalid required fields.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Email already exists.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
          description: The user's email address.
          example: newuser@example.com
        password:
          type: string
          description: The user's password.
          example: $newPassword123
        first_name:
          type: string
          description: The user's first name.
          example: Jane
        last_name:
          type: string
          description: The user's last name.
          example: Smith
        gender:
          type: string
          description: The user's gender (e.g., "Male", "Female", "Other").
          example: female
          enum:
          - male
          - female
          - other
          - default: Other
        birth_year:
          type: integer
          description: The user's birth_year must be > 1900 and <  $(currentYear).
          minimum: 1900
          maximum: $(currentYear)
          default: $(currentYear)
        birth_month:
          type: integer
          description: The user's birth_month must be between 1 and 12.
          minimum: 1
          maximum: 12
          default: 1
        birth_day:
          type: integer
          description: The user's birth_day must be between 1 and 31.
          minimum: 1
          maximum: 31
      required:
      - email
      - password
      - first_name
      - last_name
      - gender
      - birth_year
      - birth_month
      - birth_day
    RegisterResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        code:
          type: string
          example: REGISTRATION_SUCCESS
        message:
          type: string
          example: Registration successful. Please check your email to verify your account.
        data:
          type: object
          properties:
            user:
              type: object
              properties:
                id:
                  type: string
                  example: 648f72ec3e29c9e2548d9a3f
                username:
                  type: string
                  example: newUser
                first_name:
                  type: string
                  example: Jane
                last_name:
                  type: string
                  example: Smith
                picture:
                  type: string
                  example: https://res.cloudinary.com/dxos5na7j/image/upload/v1731177858/assets/images/hno2u07pzd3xh3pu5z3b.png
                verified:
                  type: boolean
                  example: false

    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          example: error
        code:
          type: string
          example: INVALID_INPUT
        message:
          type: string
          example: Invalid input data.
