swagger: '2.0'
info:
  title: User Authentication API
  version: 1.0.0
  description: API for user authentication, including sending verification emails.
paths:
  /api/auth/sendVerification:
    post:
      summary: Send email verification link
      description: Sends a verification email to the authenticated user's registered email address. The verification email contains a link to verify the user's email address.
      security:
        - BearerAuth: []
      tags:
        - Authentication
      responses:
        '200':
          description: Verification email sent successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  code:
                    type: string
                    example: VERIFICATION_EMAIL_SENT
                  message:
                    type: string
                    example: Verification email has been sent to your registered email address.
        '400':
          description: Email already activated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: EMAIL_ALREADY_ACTIVATED
                  message:
                    type: string
                    example: This email is already activated.
        '404':
          description: User not found or unauthorized.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: USER_NOT_FOUND
                  message:
                    type: string
                    example: Authenticated user not found.
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: SERVER_ERROR
                  message:
                    type: string
                    example: An unexpected error occurred. Please try again later.
