swagger: '2.0'
info:
  title: User Authentication API
  version: 1.0.0
  description: API for user authentication, including password reset functionality.
paths:
  /api/auth/sendResetPasswordCode:
    post:
      summary: Send a reset code to the user
      description: This endpoint sends a password reset code to the user's email if the email is valid and associated with an existing account.
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
                  description: The email address of the user requesting a password reset.
                  example: user@example.com
      responses:
        '200':
          description: Reset code sent successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  code:
                    type: string
                    example: RESET_CODE_SUCCESS
                  message:
                    type: string
                    example: Reset code sent successfully. Please check your email.
        '400':
          description: Invalid email address.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: INVALID_EMAIL
                  message:
                    type: string
                    example: Invalid email address.
        '404':
          description: User not found with this email address.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: USER_NOT_FOUND
                  message:
                    type: string
                    example: User not found with this email address.
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: SERVER_ERROR
                  message:
                    type: string
                    example: An unexpected error occurred. Please try again later.
