swagger: '2.0'
info:
  title: User Authentication API
  version: 1.0.0
  
paths:
  /api/auth/validateResetCode:
    post:
      summary: Validate a reset code for password recovery
      description: API for user authentication, including validating reset codes for password recovery.
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - code
              properties:
                email:
                  type: string
                  format: email
                  description: The email address of the user.
                  example: user@example.com
                code:
                  type: string
                  description: The reset code sent to the user's email.
                  example: "123456"
      responses:
        '200':
          description: Reset code validated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  code:
                    type: string
                    example: RESET_CODE_VALIDATED
                  message:
                    type: string
                    example: Reset code has been validated successfully.
        '401':
          description: Invalid reset code
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: INVALID_RESET_CODE
                  message:
                    type: string
                    example: Invalid reset code. Please check the code and try again.
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: USER_NOT_FOUND
                  message:
                    type: string
                    example: User not found with this email address.
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: SERVER_ERROR
                  message:
                    type: string
                    example: An unexpected error occurred. Please try again later.
