swagger: '2.0'
info:
  title: User Authentication API
  version: 1.0.0
  description: API for user authentication, including verifying a user's email.
paths:
  /api/auth/verify-email:
    post:
      summary: Verify a user's email
      description: Verifies the email of an authenticated user using a provided activation token.
      security:
        - BearerAuth: []
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                  description: The email activation token received by the user.
              required:
                - token
      responses:
        '200':
          description: Email has been successfully verified.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  code:
                    type: string
                    example: EMAIL_ACTIVATION_SUCCESS
                  message:
                    type: string
                    example: Email has been successfully verified. You can now log in.
        '400':
          description: Missing or invalid activation token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: INVALID_ACCESS_TOKEN
                  message:
                    type: string
                    example: Activation token is missing.
        '403':
          description: Unauthorized access to verify the email.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: INVALID_ACCESS_TOKEN
                  message:
                    type: string
                    example: You don't have authorization to complete this operation.
        '404':
          description: Authenticated user not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: USER_NOT_FOUND
                  message:
                    type: string
                    example: Authenticated user not found.
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  code:
                    type: string
                    example: SERVER_ERROR
                  message:
                    type: string
                    example: An unexpected error occurred. Please try again later.
